# Generated by Django 3.2.7 on 2021-11-21 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=100, verbose_name='Strasse')),
                ('city', models.CharField(max_length=100, verbose_name='Ort')),
                ('building_type', models.CharField(choices=[('EFH', 'Einfamilienhaus'), ('MFH', 'Mehrfamilienhaus'), ('GEW', 'Gewerbebau')], default='EFH', max_length=50, verbose_name='Gebäudeart')),
                ('year_construction', models.DateField(verbose_name='Baujahr')),
                ('ebf', models.IntegerField(verbose_name='Energiebezugsfläche [m2]')),
                ('tenant', models.IntegerField(verbose_name='Anzahl Bewohner')),
                ('heating_type', models.CharField(choices=[('OHK', 'Ölheizkessel'), ('EHK', 'Erdgasheizkessel'), ('ESH', 'Elektro-Speicherheizung'), ('EZH', 'Elektro-Zentralheizung'), ('WPL', 'Wärmepumpe Luft-Wasser'), ('WPS', 'Wärmepumpe Sole-Wasser')], default='OH', max_length=50, verbose_name='Wärmeerzeugung')),
                ('distribution_type', models.CharField(choices=[('HK', 'Heizkörper'), ('FB', 'Fussbodenheizung')], default='HK', max_length=50, verbose_name='Wärmeabgabesystem')),
                ('hotwater_type', models.CharField(choices=[('HG', 'Heizung ganzjährig'), ('HH', 'Heizung nur Heizperiode'), ('EL', 'Elektrisch'), ('WP', 'Wärmepumpenboiler'), ('SK', 'Solarkollektoren')], default='VH', max_length=50, verbose_name='Wassererwärmung')),
                ('comment', models.TextField(default='-', max_length=200, verbose_name='Kommentar [-]')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('counter_type', models.CharField(choices=[('HLM', 'Heizölzähler Mechanisch'), ('HLP', 'Heizölzähler Pneumatisch'), ('HLD', 'Heizölzähler Digital'), ('EDG', 'Erdgaszähler'), ('SET', 'Stromzähler Einfachtarif'), ('SDT', 'Stromzähler Doppeltarif')], default='EDG', max_length=50, verbose_name='Typ')),
                ('conversion', models.FloatField(default=11.452, help_text='Heizöl: X[Lit/cm], X[Lit/%], 1[Lit], Erdgas 11.452 [kWh/m3], Strom 1[kWhel]', verbose_name='Wandlerfaktor')),
                ('counter_overflow', models.BooleanField(verbose_name='Überlauf')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emtapp.building')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Readout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readout_date', models.DateField(verbose_name='Ablesedatum')),
                ('register_1', models.IntegerField(help_text='Werte ohne Komma eingeben', verbose_name='Zählerstand Register Nr.1')),
                ('register_2', models.IntegerField(default=0, help_text='Werte ohne Komma eingeben', verbose_name='Zählerstand Register Nr.2 (Nur wenn vorhanden)')),
                ('comment', models.TextField(default='-', max_length=200, verbose_name='Kommentar [-]')),
                ('energy_1', models.IntegerField(verbose_name='Energie Register Nr.1 [kWh]')),
                ('energy_2', models.IntegerField(default=0, verbose_name='Energie Register Nr.2 [kWh]')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emtapp.counter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
