# Generated by Django 3.2.7 on 2021-11-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='comment',
            field=models.TextField(default='-', max_length=200, verbose_name='Kommentar [-]'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='conversion',
            field=models.FloatField(default=1, help_text='Heizöl: X[Lit/cm], X[Lit/%], 1[Lit], Erdgas 11.452 [kWh/m3], Strom 1[kWhel]', verbose_name='Wandlungsfaktor'),
        ),
    ]
